#!/bin/bash
# Author : SUkhdeep Singh
# Organization : Max Planck Soceity

echo "Shell Script to remove random chromosomes from a BAM file";

# filename is random variable and samtools process the input bam file and thne piped to egrep
rand=$RANDOM
file=$1
du -hs $1 > "$file.$rand"
#samtools view $1 | egrep -w 'chr1|chr2|chr3|chr4|chr5|chr6|chr7|chr8|chr9|chr10|chr11|chr12|chr13|chr14|chr15|chr16|chr17|chr18|chr19|chrX|chrY|chrM' > "$rand.chrClean"
echo "Done $rand.chrClean produced"

#################################################################################################################################################################
